apiVersion: v1
kind: Service
metadata:
    name: "{{ .Chart.Name }}-service"
    labels:
        app: "{{ .Chart.Name }}"
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
spec:
    type: {{ .Values.serviceType }}
    ports:
    {{- if eq "LoadBalancer" .Values.serviceType }}
    - name: game-client-port
      port: {{ .Values.env.gameClientPort | int }}
      targetPort: game-client-port
      protocol: UDP
    - name: raw-udp-port
      port: {{ .Values.env.udpSocketPort | int }}
      targetPort: raw-udp-port
      protocol: UDP
    - name: rcon-port
      port: {{ .Values.env.rconPort | int }}
      targetPort: rcon-port
      protocol: TCP
    - name: server-list-port
      port: {{ .Values.env.serverListPort | int }}
      targetPort: server-list-port
      protocol: UDP
    {{- else }}
    - name: game-client-port
      port: {{ .Values.env.gameClientPort | int }}
      targetPort: game-client-port
      nodePort: {{ .Values.env.gameClientPort | int }}
      protocol: UDP
    - name: raw-udp-port
      port: {{ .Values.env.udpSocketPort | int }}
      targetPort: raw-udp-port
      nodePort: {{ .Values.env.udpSocketPort | int }}
      protocol: UDP
    - name: rcon-port
      port: {{ .Values.env.rconPort | int }}
      targetPort: rcon-port
      nodePort: {{ .Values.env.rconPort | int }}
      protocol: TCP
    - name: server-list-port
      port: {{ .Values.env.serverListPort | int }}
      targetPort: server-list-port
      nodePort: {{ .Values.env.serverListPort | int }}
      protocol: UDP
    {{- end }}
    selector:
        app: "{{ .Chart.Name }}"
